# Generated by Django 6.0.6 on 2026-07-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savings',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savings',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
