"""
Django settings for nmmApp project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-4yw+1e8luzflj80e##5ygd^gmi%*dq=_4f6k4u+y!6-v=%&44=')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

JAZZMIN_SETTINGS = {
    'site_title':        'NMM Admin',
    'site_header':       'NMM Budget Tracker',
    'site_brand':        'NMM',
    'site_logo':         'images/logo.png',
    'site_logo_classes': 'img-circle',
    'login_logo':        'images/logo.png',
    'login_logo_dark':   'images/logo.png',
    'site_icon':         'images/logo.png',
    'welcome_sign':      'Welcome back, Admin 👋',
    'copyright':         'NMM Budget Tracker © 2026',
    'show_sidebar':      True,
    'navigation_expanded': True,
    'hide_apps':         [],
    'hide_models':       [],
    'order_with_respect_to': ['api', 'auth'],
    'icons': {
        'auth':               'fas fa-shield-alt',
        'auth.user':          'fas fa-users',
        'auth.Group':         'fas fa-layer-group',
        'api.expense':        'fas fa-money-bill-wave',
        'api.income':         'fas fa-wallet',
        'api.savings':        'fas fa-piggy-bank',
        'api.userprofile':    'fas fa-user-circle',
    },
    'default_icon_parents':  'fas fa-chevron-circle-right',
    'default_icon_children': 'fas fa-circle',
    'related_modal_active':  True,
    'custom_css':  'css/admin_custom.css',
    'custom_js':   None,
    'use_google_fonts_cdn': True,
    'show_ui_builder': False,
    'changeform_format': 'horizontal_tabs',
    'topmenu_links': [
        {'name': '🏠 Dashboard', 'url': '/dashboard/', 'new_window': False},
        {'name': '📊 Reports',   'url': '/reports/',   'new_window': False},
        {'name': '💰 Savings',   'url': '/savings/',   'new_window': False},
    ],
    'usermenu_links': [
        {'name': 'NMM Dashboard', 'url': '/dashboard/', 'icon': 'fas fa-chart-line'},
    ],
}

JAZZMIN_UI_TWEAKS = {
    'navbar_small_text':          False,
    'footer_small_text':          True,
    'body_small_text':            False,
    'brand_small_text':           False,
    'brand_colour':               'navbar-dark',
    'accent':                     'accent-primary',
    'navbar':                     'navbar-dark',
    'no_navbar_border':           True,
    'navbar_fixed':               True,
    'layout_boxed':               False,
    'footer_fixed':               False,
    'sidebar_fixed':              True,
    'sidebar':                    'sidebar-dark-primary',
    'sidebar_nav_small_text':     False,
    'sidebar_disable_expand':     False,
    'sidebar_nav_child_indent':   True,
    'sidebar_nav_compact_style':  True,
    'sidebar_nav_legacy_style':   False,
    'sidebar_nav_flat_style':     False,
    'theme':                      'darkly',
    'dark_mode_theme':            'darkly',
    'button_classes': {
        'primary':   'btn-primary',
        'secondary': 'btn-secondary',
        'info':      'btn-info',
        'warning':   'btn-warning',
        'danger':    'btn-danger',
        'success':   'btn-success',
    },
}

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'corsheaders',
    # Local
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Allow Flutter app (any origin in development)
CORS_ALLOW_ALL_ORIGINS = True

# JWT + DRF settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

ROOT_URLCONF = 'nmmApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nmmApp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
